name: build
on: [push, pull_request,workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Build
        run: hack/build.sh
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v3
        with:
          name: openshift-install
          path: bin/openshift-install